version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    working_dir: /build/flask_middleware
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
 #   depends_on:
 #     - scgms-core

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    restart: unless-stopped
    environment:
      - VITE_BACKEND_PORT=${BACKEND_PORT}
#  scgms-core:
#    image: scgms-prebuilt-release
#    build:
#      context: ./backend
#      dockerfile: Dockerfile.scgms-release
